apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: eddie1322/payment-service:latest
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_URI
              value: mongodb://sneaker-mongo-srv:27017/payment
